name: New issue
description: Create new issue
title: "New issue"
labels:
  - test labels
assignees:
  - test assignees
body:
  - type: markdown
    attributes:
      value: |
        ### **Test**
        Test
