name: Enhancement
description: Create an issue for enhancement.
title: "[enhancement]: "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        ### **Enhancement description**
        A clear and concise description of the enhancement.

  - type: textarea
    id: what-enhancement
    attributes:
      label: What enhancement?
      placeholder: |
        Tell us what you would like to see!
        Attach screenshots if available.
    validations:
      required: true
  - type: dropdown
    id: who-work-on-this-issue
    attributes:
      label: Are you going to work on this issue yourself?
      multiple: true
      options:
        - This issue is free for anyone to take
        - I will work on this issue myself
      default: 0
